name: Run Staging Query on BigQuery

on:
  workflow_dispatch:
  push:
    paths:
      - 'sql/staging/*.sql'

jobs:
  run-staging-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: grand-water-473707-r8
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Service Account
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Execute staging_parkbee_garages.sql
        run: |
          bq query --use_legacy_sql=false < sql/staging/staging_parkbee_garages.sql
